FROM docker.io/golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o swiperproxy ./cmd/swiperproxy

FROM docker.io/alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /root/

COPY --from=builder /app/swiperproxy .
COPY --from=builder /app/configs/config.yaml ./configs/

EXPOSE 8080

CMD ["./swiperproxy", "-config", "configs/config.yaml"]